In [2]:
import pandas as pd 
from pymongo import MongoClient

# Connect to MongoDB
client = MongoClient("mongodb://localhost:27017/")

# Create or access database
db = client["staging_db"]

# Create or access collection
collection = db["mercedes-benz_jobs"]

print("Connected successfully!")

Connected successfully!

In [5]:
data = list(collection.find())

df = pd.DataFrame(data)

# Clean MongoDB artifacts
df["_id"] = df["_id"].astype(str)

# Optional: keep only useful columns
df = df[[
    "job_id",
    "title",
    "job_category",
    "start_date",
    "publication",
    "organization",
    "Department",
    "working_mode",
    "location",
    "description"
]]

print(df.head())

       job_id                                              title  \
0  MER000441Q  Manager, Public Relations | Mercedes-Benz > Ca...
1  MER0003T59  Assistant Manager, Tax Specialist | Mercedes-B...
2  MER00044DU  Process Engineer – Automation & Controls | Mer...
3  MER00044DN  Full Stack Developer - HUD Miner | Mercedes-Be...
4  MER0003ZHY  C# .NET Developer | Mercedes-Benz > Career > J...

                            job_category   start_date publication  \
0                                 Others   01.08.2026  15.06.2026
1                    Finance/Controlling  immediately  15.06.2026
2                             Production  immediately  15.06.2026
3  Research and Development incl. Design   01.07.2026  15.06.2026
4  Research and Development incl. Design  immediately  15.06.2026

                                        organization  \
0                   Mercedes-Benz Malaysia Sdn. Bhd.
1                   Mercedes-Benz Malaysia Sdn. Bhd.
2     Mercedes-Benz Manufacturing Poland sp. z o. o.
3  Mercedes-Benz Research and Development India P...
4  Mercedes-Benz Research and Development India P...

                     Department working_mode  \
0       SEA Marketing & Digital    Full time
1  Finance & Controlling MBPLAP    Full time
2                   Engineering    Full time
3         Production Planning 1    Full time
4         Central Data Products    Full time

                                            location  \
0     Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur
1     Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur
2  Mercedes-Benz Manufacturing Poland sp. z o. o....
3  Mercedes-Benz Research and Development India P...
4  Mercedes-Benz Research and Development India P...

                                         description
0  TasksOBJECTIVE OF JOB·        Develop, plan, a...
1  TasksObjective of JobResponsible for managing ...
2  TasksLooking for new challenges? The term "aut...
3  TasksAbout MBRDI:Mercedes-Benz Research and De...
4  TasksRole: .NET Developer (C#)Experience: +5 y...

In [6]:
df.head()

,job_id,title,job_category,start_date,publication,organization,Department,working_mode,location,description
0,MER000441Q,"Manager, Public Relations | Mercedes-Benz > Ca...",Others,01.08.2026,15.06.2026,Mercedes-Benz Malaysia Sdn. Bhd.,SEA Marketing & Digital,Full time,"Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur","TasksOBJECTIVE OF JOB· Develop, plan, a..."
1,MER0003T59,"Assistant Manager, Tax Specialist | Mercedes-B...",Finance/Controlling,immediately,15.06.2026,Mercedes-Benz Malaysia Sdn. Bhd.,Finance & Controlling MBPLAP,Full time,"Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur",TasksObjective of JobResponsible for managing ...
2,MER00044DU,Process Engineer – Automation & Controls | Mer...,Production,immediately,15.06.2026,Mercedes-Benz Manufacturing Poland sp. z o. o.,Engineering,Full time,Mercedes-Benz Manufacturing Poland sp. z o. o....,"TasksLooking for new challenges? The term ""aut..."
3,MER00044DN,Full Stack Developer - HUD Miner | Mercedes-Be...,Research and Development incl. Design,01.07.2026,15.06.2026,Mercedes-Benz Research and Development India P...,Production Planning 1,Full time,Mercedes-Benz Research and Development India P...,TasksAbout MBRDI:Mercedes-Benz Research and De...
4,MER0003ZHY,C# .NET Developer | Mercedes-Benz > Career > J...,Research and Development incl. Design,immediately,15.06.2026,Mercedes-Benz Research and Development India P...,Central Data Products,Full time,Mercedes-Benz Research and Development India P...,TasksRole: .NET Developer (C#)Experience: +5 y...

# Data Understanding

In [7]:
df.shape

(1120, 10)

In [8]:
df.columns

Index(['job_id', 'title', 'job_category', 'start_date', 'publication',
       'organization', 'Department', 'working_mode', 'location',
       'description'],
      dtype='str')

## Duplicates Identification

In [9]:
df.duplicated().sum()

np.int64(62)

In [10]:
df[df.duplicated]

,job_id,title,job_category,start_date,publication,organization,Department,working_mode,location,description
40,MER000441Q,"Manager, Public Relations | Mercedes-Benz > Ca...",Others,01.08.2026,15.06.2026,Mercedes-Benz Malaysia Sdn. Bhd.,SEA Marketing & Digital,Full time,"Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur","TasksOBJECTIVE OF JOB· Develop, plan, a..."
41,MER0003T59,"Assistant Manager, Tax Specialist | Mercedes-B...",Finance/Controlling,immediately,15.06.2026,Mercedes-Benz Malaysia Sdn. Bhd.,Finance & Controlling MBPLAP,Full time,"Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur",TasksObjective of JobResponsible for managing ...
42,MER00044DU,Process Engineer – Automation & Controls | Mer...,Production,immediately,15.06.2026,Mercedes-Benz Manufacturing Poland sp. z o. o.,Engineering,Full time,Mercedes-Benz Manufacturing Poland sp. z o. o....,"TasksLooking for new challenges? The term ""aut..."
43,MER00044DN,Full Stack Developer - HUD Miner | Mercedes-Be...,Research and Development incl. Design,01.07.2026,15.06.2026,Mercedes-Benz Research and Development India P...,Production Planning 1,Full time,Mercedes-Benz Research and Development India P...,TasksAbout MBRDI:Mercedes-Benz Research and De...
44,MER0003ZHY,C# .NET Developer | Mercedes-Benz > Career > J...,Research and Development incl. Design,immediately,15.06.2026,Mercedes-Benz Research and Development India P...,Central Data Products,Full time,Mercedes-Benz Research and Development India P...,TasksRole: .NET Developer (C#)Experience: +5 y...
...,...,...,...,...,...,...,...,...,...,...
1060,MER00041VD,Drive Systems – Thermal Management Function En...,Research and Development incl. Design,01.07.2026,29.04.2026,Mercedes-Benz Group China Ltd.,Drive Systems Function I,Full time,"Mercedes-Benz Group China Ltd., Beijing",TasksObjectives: Calibrate and optimize the th...
1080,MER0003VML,Vehicle Functions Android Developer | Mercedes...,Research and Development incl. Design,immediately,23.04.2026,Mercedes-Benz Research and Development India P...,"Infotainment, UI, Interior sensing",Full time,Mercedes-Benz Research and Development India P...,TasksAbout MBRDI:Mercedes-Benz Research and De...
1090,MER000404Y,Technical Lead - Cloud Backend Developer | Mer...,Research and Development incl. Design,immediately,22.04.2026,Mercedes-Benz Research and Development India P...,"Cloud, Data & Connected Services",Full time,Mercedes-Benz Research and Development India P...,"TasksKey ResponsibilitiesDesign, develop, and ..."
1100,MER00040RB,ITSM / Major Incident & Operations Specialist ...,IT/Telecommunications,immediately,20.04.2026,Mercedes-Benz Research and Development India P...,Client & Platforms,Full time,Mercedes-Benz Research and Development India P...,TasksJob Title ITSM –Major Incident & Operatio...
1101,MER00041BM,Sr. SW Engineer for Unified Data Collector | M...,Research and Development incl. Design,immediately,20.04.2026,Mercedes-Benz Research and Development India P...,"Infotainment, UI, Interior sensing",Full time,Mercedes-Benz Research and Development India P...,TasksAbout MBRDI:Mercedes-Benz Research and De...

In [15]:
df.drop_duplicates(inplace=True)

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.shape

(1058, 10)

## Checking missing values

In [19]:
df.isna().sum()

job_id           0
title            0
job_category     0
start_date       5
publication      0
organization     0
Department      24
working_mode     5
location         0
description      0
dtype: int64

In [23]:
df_dt = df.copy()

In [24]:
df_dt = df_dt[~df.Department.isna()]

In [26]:
df_dt.isna().sum()

job_id          0
title           0
job_category    0
start_date      0
publication     0
organization    0
Department      0
working_mode    5
location        0
description     0
dtype: int64

In [27]:
df_dt = df_dt[~df_dt.working_mode.isna()]

In [28]:
df_dt.isna().sum()

job_id          0
title           0
job_category    0
start_date      0
publication     0
organization    0
Department      0
working_mode    0
location        0
description     0
dtype: int64

In [37]:
jobs_df = df_dt.copy()

## Understanding distribution of data

In [38]:
jobs_df.job_category.nunique()

15

In [39]:
pd.unique(jobs_df.job_category)

<ArrowStringArray>
[                               'Others',
                   'Finance/Controlling',
                            'Production',
 'Research and Development incl. Design',
                 'IT/Telecommunications',
                                    'HR',
    'Marketing / Sales / Communications',
                 'Administration/Office',
           'Corporate planning/strategy',
                    'Quality Management',
                           'Procurement',
               'Supply Chain Management',
                'Environment protection',
             'Finance/Leasing & Banking',
                  'Organization and Law']
Length: 15, dtype: str

In [40]:
jobs_df.organization.nunique()

45

In [41]:
jobs_df.organization.value_counts()

organization
Mercedes-Benz AG                                                   501
Mercedes-Benz Research and Development India Private Limited       173
Mercedes-Benz Group China Ltd.                                     125
Mercedes-Benz Vans, LLC                                             27
Mercedes-Benz Group AG                                              26
Mercedes-Benz Manufacturing Hungary Kft.                            23
Mercedes-Benz Digital Tech Ltd.                                     16
Mercedes-Benz Manufacturing Poland sp. z o. o.                      13
Mercedes-Benz U.S. International, Inc.                              11
Mercedes-Benz USA, LLC                                              10
Mercedes-Benz Financial Services USA LLC                             8
Mercedes-Benz Ludwigsfelde GmbH                                      8
Mercedes-Benz G GmbH                                                 8
Mercedes-Benz Gastronomie GmbH                                       6
Mercedes-Benz Vietnam Ltd.                                           6
Mercedes-Benz Canada Inc.                                            5
Mercedes-Benz Bank AG                                                5
Mercedes-Benz Group Services Poland Sp.z o.o.                        5
Mercedes-Benz Korea Limited                                          5
Mercedes-Benz Logistics and Distribution Egypt LLC                   5
Mercedes-Benz Malaysia Sdn. Bhd.                                     4
Mercedes-Benz Customer Solutions GmbH                                4
Mercedes-Benz Japan G.K.                                             4
Mercedes-Benz Espana, S.A.U.                                         3
Mercedes-Benz Automotive Mobility GmbH                               3
Mercedes-Benz Taiwan Ltd.                                            3
Mercedes-Benz Mobility & Technology Service (Beijing) Co., Ltd.      2
Mercedes-Benz Heritage GmbH                                          2
Mercedes-Benz Bank Service Center GmbH                               2
Mercedes-Benz  North America Corporation                             1
Mercedes-Benz Used Parts & Services GmbH                             1
Mercedes-Benz Financial Services India Private Limited               1
Mercedes-Benz Financial Services UK Limited                          1
Mercedes-Benz UK Limited                                             1
Mercedes-Benz Mobility (Thailand) Co., Ltd.                          1
Mercedes-Benz Financial Services France S.A.                         1
Mercedes-Benz France S.A.S.                                          1
Mercedes-Benz Energy GmbH                                            1
Mercedes-Benz Cars Middle East FZE                                   1
Mercedes-Benz Connectivity Services GmbH                             1
Mercedes-Benz Services Malaysia Sdn Bhd                              1
Mercedes-Benz (Thailand) Limited                                     1
Mercedes-Benz Banking Service GmbH                                   1
Mercedes-Benz Grund Services GmbH                                    1
Mercedes-Benz Finance Co., Ltd.                                      1
Name: count, dtype: int64

In [42]:
jobs_df.Department.nunique()

656

In [43]:
pd.unique(jobs_df.Department)

<ArrowStringArray>
[                                    'SEA Marketing & Digital',
                                'Finance & Controlling MBPLAP',
                                                 'Engineering',
                                       'Production Planning 1',
                                       'Central Data Products',
       'Ramp up Plant & Digitalization: Omniverse & Mfg. Engg',
                                                'PICAO - SUMS',
         'Software- & Funktionsentwicklung THK & LQ MB.OS 2.0',
                                          'Werkstatt-Team PKW',
                             'Ferienbeschäftigung HR Services',
 ...
                        'Marketing & Recruiting Greater China',
                                                'Assembly -HU',
                                                'LCM - VAN/EF',
 'Module,Equipm.,IE,Series,Quality&BEMI planning: MIB/M-S/QPP',
                                          'Client & Platforms',
                            '3d Engineering - CAD Development',
                         'Technische Berufsausbildung Hamburg',
                               'Werkstatt-Team NFZ Hildesheim',
                                            'Legal MBFS Japan',
                            'LDL-Management Ladungsträger W10']
Length: 656, dtype: str

In [44]:
jobs_df.working_mode.nunique()

3

In [45]:
pd.unique(jobs_df.working_mode)

<ArrowStringArray>
['Full time', 'Full time (part time possible)', 'Part time']
Length: 3, dtype: str

# Translate language to English

In [72]:
from langdetect import detect
from deep_translator import GoogleTranslator

def translate_to_english(text):
    try:
        lang = detect(text)

        if lang == "en":
            return text

        translated = GoogleTranslator(source=lang, target="en").translate(text)
        return translated

    except:
        return text  # fallback if detection fails

In [73]:
jobs_df["description_en"] = jobs_df["description"].apply(translate_to_english)

# Cleaning Description

In [97]:
jobs_list = jobs_df.description_en.to_list()

In [ ]:
import re

results = []

for idx, job in enumerate(jobs_list):

    text = job

    # -----------------------------
    # 1. TASK DETECTION
    # -----------------------------
    task_match = re.search(r'(?i)Tasks', text)

    # -----------------------------
    # 2. QUALIFICATION DETECTION (ALL YOUR PATTERNS IN ORDER)
    # -----------------------------
    qual_match = None

    patterns = [
        r'(?i)(?:^|[\s\n]|(?<=[a-z]))Qualifications(?:[\s\n]|(?=[A-Z])|$)',
        r'(?i)(?:^|[^A-Za-z0-9])Qualifications(?:$|[^A-Za-z0-9])',
        r'(?i)\bQualifications(?:Qualification)?\b',
        r'(?i)Qualifications(?:Qualification)?'   # fallback for merged OCR cases
    ]

    for p in patterns:
        qual_match = re.search(p, text)
        if qual_match:
            break

    # -----------------------------
    # DEFAULTS
    # -----------------------------
    task_text = text
    qual_text = None
    qual_flag = "Not found"

    # -----------------------------
    # CASE A: BOTH FOUND
    # -----------------------------
    if task_match and qual_match:

        task_text = text[task_match.end():qual_match.start()]
        qual_text = text[qual_match.end():]

        qual_flag = "Found"

    # -----------------------------
    # CASE B: ONLY TASK FOUND
    # -----------------------------
    elif task_match and not qual_match:

        task_text = text[task_match.end():]
        qual_text = None
        qual_flag = "Not found"

    # -----------------------------
    # CASE C: ONLY QUALIFICATION FOUND
    # -----------------------------
    elif qual_match and not task_match:

        task_text = text[:qual_match.start()]
        qual_text = text[qual_match.end():]
        qual_flag = "Found"

    # -----------------------------
    # CASE D: NONE FOUND
    # -----------------------------
    else:

        task_text = text
        qual_text = None
        qual_flag = "Not found"

    # -----------------------------
    # STORE RESULT
    # -----------------------------
    results.append({
        "index": idx,
        "tasks": task_text.strip(),
        "qualifications": qual_text.strip() if qual_text else None,
        "qualification_flag": qual_flag
    })

    print(idx, qual_flag)

In [ ]:
results[10:30]

In [109]:
results[0]["tasks"]

'OBJECTIVE OF JOB·\xa0\xa0\xa0\xa0\xa0\xa0\xa0 Develop, plan, and execute MB Malaysia’s corporate communication & PR strategy to position MBM as a leader in the Malaysian automotive industry and a socially responsible corporate citizen.·\xa0\xa0\xa0\xa0\xa0\xa0\xa0 Drive integrated communications strategies across earned media, search, and AI-driven discovery platforms, leveraging GEO (Generative Engine Optimization) and AEO (Answer Engine Optimization) to strengthen brand visibility, authority, and customer engagement.·\xa0\xa0\xa0\xa0\xa0\xa0\xa0 Champion internal communication strategies to achieve a two-way communication environment that fosters higher morale, greater productivity, and a strong corporate culture.·\xa0\xa0\xa0\xa0\xa0\xa0\xa0 Establish and enhance relationships with external partners including media & influencers, not excluding NGOs and the corporate community, to effectively communicate MB Malaysia’s brand presence and image while providing dedicated support.·\xa0\xa0\xa0\xa0\xa0\xa0\xa0 Oversee MB Malaysia’s Sponsorship and Donation Database.·\xa0\xa0\xa0\xa0\xa0\xa0\xa0 Oversee and integrate PR and Social Media strategy to enhance brand visibility, audience engagement, and corporate reputation.·\xa0\xa0\xa0\xa0\xa0\xa0\xa0 Lead the company’s social media marketing activation efforts, including postings for CS, MB Financial, for enhanced engagement in support of the overall Marketing campaigns.\xa0JOB DESCRIPTION1.\xa0\xa0\xa0\xa0\xa0\xa0 Develop, plan, and execute Corporate PR, marketing events, sponsorships, and donation projects in line with MBM’s corporate strategy. Includes interviews, press releases, and event organization.2.\xa0\xa0\xa0\xa0\xa0\xa0 Manage and oversee Social Media content strategy, audience engagement, and corporate reputation across digital platforms. Ensure timely and relevant content aligned with corporate goals.3.\xa0\xa0\xa0\xa0\xa0\xa0 Social media management – oversee content strategy, engagement, and crisis communication on digital platforms4.\xa0\xa0\xa0\xa0\xa0\xa0 Establish and maintain relationships with external media (business, finance, social, political, NGOs, Government). Includes networking, media briefings, and press relations.5.\xa0\xa0\xa0\xa0\xa0\xa0 Support business units in corporate PR, brand identity, and event execution to align with MBM’s messaging6.\xa0\xa0\xa0\xa0\xa0\xa0 Establish and monitor corporate identity to maintain a consistent brand image.7.\xa0\xa0\xa0\xa0\xa0\xa0 Develop and execute Internal Communication tools, including the company’s social intranet8.\xa0\xa0\xa0\xa0\xa0\xa0 Monitor coverage and market trends and research consumer behaviors for strategic insights via media coverage and social media listening'

In [110]:
jobs_df["jd_tasks"] = [task["tasks"] for task in results]

In [111]:
jobs_df.head()

,job_id,title,job_category,start_date,publication,organization,Department,working_mode,location,description,description_en,jd_tasks
0,MER000441Q,"Manager, Public Relations | Mercedes-Benz > Ca...",Others,01.08.2026,15.06.2026,Mercedes-Benz Malaysia Sdn. Bhd.,SEA Marketing & Digital,Full time,"Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur","TasksOBJECTIVE OF JOB· Develop, plan, a...","TasksOBJECTIVE OF JOB· Develop, plan, a...","OBJECTIVE OF JOB· Develop, plan, and ex..."
1,MER0003T59,"Assistant Manager, Tax Specialist | Mercedes-B...",Finance/Controlling,immediately,15.06.2026,Mercedes-Benz Malaysia Sdn. Bhd.,Finance & Controlling MBPLAP,Full time,"Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur",TasksObjective of JobResponsible for managing ...,TasksObjective of JobResponsible for managing ...,Objective of JobResponsible for managing organ...
2,MER00044DU,Process Engineer – Automation & Controls | Mer...,Production,immediately,15.06.2026,Mercedes-Benz Manufacturing Poland sp. z o. o.,Engineering,Full time,Mercedes-Benz Manufacturing Poland sp. z o. o....,"TasksLooking for new challenges? The term ""aut...","TasksLooking for new challenges? The term ""aut...","Looking for new challenges? The term ""automati..."
3,MER00044DN,Full Stack Developer - HUD Miner | Mercedes-Be...,Research and Development incl. Design,01.07.2026,15.06.2026,Mercedes-Benz Research and Development India P...,Production Planning 1,Full time,Mercedes-Benz Research and Development India P...,TasksAbout MBRDI:Mercedes-Benz Research and De...,TasksAbout MBRDI:Mercedes-Benz Research and De...,About MBRDI:Mercedes-Benz Research and Develop...
4,MER0003ZHY,C# .NET Developer | Mercedes-Benz > Career > J...,Research and Development incl. Design,immediately,15.06.2026,Mercedes-Benz Research and Development India P...,Central Data Products,Full time,Mercedes-Benz Research and Development India P...,TasksRole: .NET Developer (C#)Experience: +5 y...,TasksRole: .NET Developer (C#)Experience: +5 y...,Role: .NET Developer (C#)Experience: +5 yearsO...

In [112]:
jobs_df["jd_qualificaiton"] = [qual["qualifications"] for qual in results]

In [113]:
jobs_df.head()

,job_id,title,job_category,start_date,publication,organization,Department,working_mode,location,description,description_en,jd_tasks,jd_qualificaiton
0,MER000441Q,"Manager, Public Relations | Mercedes-Benz > Ca...",Others,01.08.2026,15.06.2026,Mercedes-Benz Malaysia Sdn. Bhd.,SEA Marketing & Digital,Full time,"Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur","TasksOBJECTIVE OF JOB· Develop, plan, a...","TasksOBJECTIVE OF JOB· Develop, plan, a...","OBJECTIVE OF JOB· Develop, plan, and ex...",EDUCATION LEVEL / TRAININGDegree in Communicat...
1,MER0003T59,"Assistant Manager, Tax Specialist | Mercedes-B...",Finance/Controlling,immediately,15.06.2026,Mercedes-Benz Malaysia Sdn. Bhd.,Finance & Controlling MBPLAP,Full time,"Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur",TasksObjective of JobResponsible for managing ...,TasksObjective of JobResponsible for managing ...,Objective of JobResponsible for managing organ...,Education Level / TrainingDegree/Advanced Dipl...
2,MER00044DU,Process Engineer – Automation & Controls | Mer...,Production,immediately,15.06.2026,Mercedes-Benz Manufacturing Poland sp. z o. o.,Engineering,Full time,Mercedes-Benz Manufacturing Poland sp. z o. o....,"TasksLooking for new challenges? The term ""aut...","TasksLooking for new challenges? The term ""aut...","Looking for new challenges? The term ""automati...",- Degree in electrical engineering with...
3,MER00044DN,Full Stack Developer - HUD Miner | Mercedes-Be...,Research and Development incl. Design,01.07.2026,15.06.2026,Mercedes-Benz Research and Development India P...,Production Planning 1,Full time,Mercedes-Benz Research and Development India P...,TasksAbout MBRDI:Mercedes-Benz Research and De...,TasksAbout MBRDI:Mercedes-Benz Research and De...,About MBRDI:Mercedes-Benz Research and Develop...,/ Good to Have:• Mercedes-Benz domain knowledg...
4,MER0003ZHY,C# .NET Developer | Mercedes-Benz > Career > J...,Research and Development incl. Design,immediately,15.06.2026,Mercedes-Benz Research and Development India P...,Central Data Products,Full time,Mercedes-Benz Research and Development India P...,TasksRole: .NET Developer (C#)Experience: +5 y...,TasksRole: .NET Developer (C#)Experience: +5 y...,Role: .NET Developer (C#)Experience: +5 yearsO...,Skills:- 5+ years of hands-on experienc...

In [114]:
jobs_df.isna().sum()

job_id              0
title               0
job_category        0
start_date          0
publication         0
organization        0
Department          0
working_mode        0
location            0
description         0
description_en      0
jd_tasks            0
jd_qualificaiton    9
dtype: int64

In [116]:
jobs_df.duplicated().sum()

np.int64(0)

In [119]:
jobs_df.to_csv("../../datasets/raw/mbnz_level1_cleaning.csv",index=False)