In [23]:
import requests
import pandas as pd
from skillNer.general_params import SKILL_DB

In [24]:
df = pd.read_csv("../../datasets/processed/integrated_data_skills_extracted.v2.csv")

In [25]:
df.head()

,job_id,title,field_of_work,posted_since,company,Department,job_type,location,clean_description,description_improved,skills_ids
0,MER000441Q,"Manager, Public Relations",Others,2026-06-15,Mercedes-Benz Malaysia Sdn. Bhd.,SEA Marketing & Digital,full time,"Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur","objective of job develop, plan, and execute mb...","Job Title: Manager, Public Relations\n ...",{'full_matches': [{'skill_id': 'KS122F16SHSGPX...
1,MER0003T59,"Assistant Manager, Tax Specialist",Finance/Controlling,2026-06-15,Mercedes-Benz Malaysia Sdn. Bhd.,Finance & Controlling MBPLAP,full time,"Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur",objective of jobresponsible for managing organ...,"Job Title: Assistant Manager, Tax Specialist\n...",{'full_matches': [{'skill_id': 'ES1BEEB0EA9BCF...
2,MER00044DU,Process Engineer – Automation & Controls,Production,2026-06-15,Mercedes-Benz Manufacturing Poland sp. z o. o.,Engineering,full time,Mercedes-Benz Manufacturing Poland sp. z o. o....,"looking for new challenges? the term ""automati...",Job Title: Process Engineer – Automation & Con...,{'full_matches': [{'skill_id': 'ESFB6F6182E69D...
3,MER00044DN,Full Stack Developer - HUD Miner,Research and Development incl. Design,2026-06-15,Mercedes-Benz Research and Development India P...,Production Planning 1,full time,Mercedes-Benz Research and Development India P...,about mbrdi:mercedes-benz research and develop...,Job Title: Full Stack Developer - HUD Miner\n ...,{'full_matches': [{'skill_id': 'KS128BK6JSSHNT...
4,MER0003ZHY,C# .NET Developer,Research and Development incl. Design,2026-06-15,Mercedes-Benz Research and Development India P...,Central Data Products,full time,Mercedes-Benz Research and Development India P...,net developer (c#)experience: +5 yearsoverview...,Job Title: C# .NET Developer\n Comp...,{'full_matches': [{'skill_id': 'KS1219N6Z3XQ19...

# Skills mapping

In [26]:
# temporary code for help 
import ast

import ast
import numpy as np
import re

def safe_parse(x):
    try:
        return ast.literal_eval(x)
    except:
        # fix numpy types like np.int64(2)
        x = re.sub(r'np\.int64\((\d+)\)', r'\1', x)
        x = re.sub(r'np\.float64\(([\d.]+)\)', r'\1', x)
        return ast.literal_eval(x)

df['results'] = df['skills_ids'].apply(safe_parse)

In [27]:
df.head()

,job_id,title,field_of_work,posted_since,company,Department,job_type,location,clean_description,description_improved,skills_ids,results
0,MER000441Q,"Manager, Public Relations",Others,2026-06-15,Mercedes-Benz Malaysia Sdn. Bhd.,SEA Marketing & Digital,full time,"Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur","objective of job develop, plan, and execute mb...","Job Title: Manager, Public Relations\n ...",{'full_matches': [{'skill_id': 'KS122F16SHSGPX...,{'full_matches': [{'skill_id': 'KS122F16SHSGPX...
1,MER0003T59,"Assistant Manager, Tax Specialist",Finance/Controlling,2026-06-15,Mercedes-Benz Malaysia Sdn. Bhd.,Finance & Controlling MBPLAP,full time,"Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur",objective of jobresponsible for managing organ...,"Job Title: Assistant Manager, Tax Specialist\n...",{'full_matches': [{'skill_id': 'ES1BEEB0EA9BCF...,{'full_matches': [{'skill_id': 'ES1BEEB0EA9BCF...
2,MER00044DU,Process Engineer – Automation & Controls,Production,2026-06-15,Mercedes-Benz Manufacturing Poland sp. z o. o.,Engineering,full time,Mercedes-Benz Manufacturing Poland sp. z o. o....,"looking for new challenges? the term ""automati...",Job Title: Process Engineer – Automation & Con...,{'full_matches': [{'skill_id': 'ESFB6F6182E69D...,{'full_matches': [{'skill_id': 'ESFB6F6182E69D...
3,MER00044DN,Full Stack Developer - HUD Miner,Research and Development incl. Design,2026-06-15,Mercedes-Benz Research and Development India P...,Production Planning 1,full time,Mercedes-Benz Research and Development India P...,about mbrdi:mercedes-benz research and develop...,Job Title: Full Stack Developer - HUD Miner\n ...,{'full_matches': [{'skill_id': 'KS128BK6JSSHNT...,{'full_matches': [{'skill_id': 'KS128BK6JSSHNT...
4,MER0003ZHY,C# .NET Developer,Research and Development incl. Design,2026-06-15,Mercedes-Benz Research and Development India P...,Central Data Products,full time,Mercedes-Benz Research and Development India P...,net developer (c#)experience: +5 yearsoverview...,Job Title: C# .NET Developer\n Comp...,{'full_matches': [{'skill_id': 'KS1219N6Z3XQ19...,{'full_matches': [{'skill_id': 'KS1219N6Z3XQ19...

In [29]:
def map_skill_names(annotations):
    try : 
        #annotations = skill_extractor.annotate(description)
        skills_maped = set()
        for skill in annotations.get("full_matches", []):
            #skills.add(skill["doc_node_value"])
            skills_maped.add(SKILL_DB[skill["skill_id"]]["skill_name"])
    
        for skill in annotations.get("ngram_scored", []):
            if skill["score"] > 0.5: 
                #skills.add(skill["doc_node_value"])
                skills_maped.add(SKILL_DB[skill["skill_id"]]["skill_name"])
            else: 
                pass 
    
        return skills_maped
    except Exception as e: 
        return None 

df["skills_maped"] = df["results"].apply(map_skill_names)

In [32]:
df.skills_maped.to_list()[1]

{'AD Model Builder (ADMB)',
 'Accounting',
 'Ad Hoc Testing',
 'Asset Management',
 'Corporate Tax',
 'Customs Declarations',
 'Data Extraction',
 'E (Programming Language)',
 'E-Invoicing',
 'Electronic Reporting Systems',
 'English Language',
 'Filing',
 'Finance',
 'Fixed Asset',
 'Fixed Asset Register',
 'Impact Assessment',
 'Income Tax',
 'Indirect Tax',
 'Malaysian Language',
 'Management',
 'Midas',
 'Month-End Closing',
 'Remittance',
 'Sales',
 'Software Defined Networking (SDN)',
 'Standard Accounting Practices',
 'Tax Compliance',
 'Tax Credit Specialist',
 'Tax Management',
 'Tax Preparation',
 'Tax Rate',
 'Tax Return',
 'Verbal Communication Skills',
 'Withholding Tax'}

In [33]:
df.drop(["skills_ids","results"],axis=1,inplace=True)

In [34]:
df.head()

,job_id,title,field_of_work,posted_since,company,Department,job_type,location,clean_description,description_improved,skills_maped
0,MER000441Q,"Manager, Public Relations",Others,2026-06-15,Mercedes-Benz Malaysia Sdn. Bhd.,SEA Marketing & Digital,full time,"Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur","objective of job develop, plan, and execute mb...","Job Title: Manager, Public Relations\n ...","{Social Media, Crisis Communications, Customer..."
1,MER0003T59,"Assistant Manager, Tax Specialist",Finance/Controlling,2026-06-15,Mercedes-Benz Malaysia Sdn. Bhd.,Finance & Controlling MBPLAP,full time,"Mercedes-Benz Malaysia Sdn. Bhd., Kuala Lumpur",objective of jobresponsible for managing organ...,"Job Title: Assistant Manager, Tax Specialist\n...","{Tax Return, E (Programming Language), Impact ..."
2,MER00044DU,Process Engineer – Automation & Controls,Production,2026-06-15,Mercedes-Benz Manufacturing Poland sp. z o. o.,Engineering,full time,Mercedes-Benz Manufacturing Poland sp. z o. o....,"looking for new challenges? the term ""automati...",Job Title: Process Engineer – Automation & Con...,"{Software Requirements Specification, Dolly Gr..."
3,MER00044DN,Full Stack Developer - HUD Miner,Research and Development incl. Design,2026-06-15,Mercedes-Benz Research and Development India P...,Production Planning 1,full time,Mercedes-Benz Research and Development India P...,about mbrdi:mercedes-benz research and develop...,Job Title: Full Stack Developer - HUD Miner\n ...,"{Agile Software Development, Artificial Lingui..."
4,MER0003ZHY,C# .NET Developer,Research and Development incl. Design,2026-06-15,Mercedes-Benz Research and Development India P...,Central Data Products,full time,Mercedes-Benz Research and Development India P...,net developer (c#)experience: +5 yearsoverview...,Job Title: C# .NET Developer\n Comp...,"{Unit Testing, Forecasting, E (Programming Lan..."

In [35]:
def clean_employment_type(text):
    text = text.lower()

    # Replace separators with spaces
    text = text.replace('-', ' ')
    return text

df["job_type"] = df.job_type.apply(clean_employment_type)

In [36]:
df['strata'] = (
    df['Department'].astype(str) + "_" +
    df['job_type'].astype(str) + "_" +
    df['location'].astype(str) + "_" +
    df['field_of_work'].astype(str)
)

In [37]:
df_sample = df.groupby('strata', group_keys=False).apply(
    lambda x: x.sample(frac=0.35, random_state=42)
)

In [38]:
df_sample.head()

,job_id,title,field_of_work,posted_since,company,Department,job_type,location,clean_description,description_improved,skills_maped
616,MER00043I2,Working student automated driving and driving ...,Research and Development incl. Design,2026-05-28,Mercedes-Benz AG,"AD Rating, Certification, & Compliance 2",part time,"Mercedes-Benz Plant Sindelfingen, Sindelfingen",in the area of ​​active safety and autonomous ...,Job Title: Working student automated driving a...,"{English Language, Industrial Engineering, Env..."
223,MER00041FN,RD/IDE - Brackets dev BTV (T9),Research and Development incl. Design,2026-09-06,Mercedes-Benz Research and Development India P...,"ADAS Sensor Integration, Sound, SUMS, EE Release",full time,Mercedes-Benz Research and Development India P...,roles & responsibilities: excellent interperso...,Job Title: RD/IDE - Brackets dev BTV (T9)\n ...,"{Geometry, T9 (Predictive Text), Data Analysis..."
121,MER0003THB,Software Engineer (Data & AI),IT/Telecommunications,2026-11-06,Mercedes-Benz Group China Ltd.,AI & Data Value,full time,"Mercedes-Benz Group China Ltd., Beijing",objective of jobcontribute to the future of me...,Job Title: Software Engineer (Data & AI)\n ...,"{PyTorch (Machine Learning Library), Data Pipe..."
610,MER00040G3,Senior Technical Specialist [NAC] [After-Sales...,Research and Development incl. Design,2026-05-28,Mercedes-Benz Research and Development India P...,"AS Engineering-DT, Diagnostics-Telem., OM, NAC...",full time,Mercedes-Benz Research and Development India P...,about mbrdimercedes-benz research and developm...,Job Title: Senior Technical Specialist [NAC] [...,"{Aftersales, Siemens Control Systems, Agile Ed..."
94,MER000440T,AD Backend Product Owner,Research and Development incl. Design,2026-11-06,Mercedes-Benz Group China Ltd.,Advanced Design Center China,full time,"Mercedes-Benz Group China Ltd., Beijing",china is the biggest passenger car market for ...,Job Title: AD Backend Product Owner\n ...,"{Java (Programming Language), E (Programming L..."

In [39]:
df.to_csv("../../datasets/processed/integrated_cleaned_dataset.v2.csv",index=False)
df_sample.to_csv("../../datasets/evaluation/sample_integrated_cleaned.v2.csv",index=False)